### ISSUE TITLE
Проблемы при установки.

### ISSUE THREAD

**Issue by HalfWorm** [A-SOM/docker-majordomo#4]
При разворачивании докера не забирает image: mariadb, поменял на image: linuxserver/mariadb  тогда взлетела.

После установки веб выдает 502

**Comment by A-SOM** [comment]
Доброго дня.
В данный момент сборка не рабочая, требуется проверить некоторые новые изменения + из за того, что debian 9 умер, некоторая часть не работае.
По поводу образа mariadb, это странно. Данный образ работает везде.

Оставлю ишью открытым пока не перетестирую.

**Comment by DjPrizrak** [comment]
mariadb не заводится на amr (типо Raspberry pi, Tinker Board).
поэтому и используем linuxserver/mariadb

**Comment by HalfWorm** [comment]
Для тестов использовалась Raspberry PI 3

**Comment by A-SOM** [comment]
> mariadb не заводится на amr (типо Raspberry pi, Tinker Board).
> поэтому и используем linuxserver/mariadb

Я вроде бы, делал опции для запуска mariadb под распберри.
В ближайшее время подолью изменение тогда под linuxserver.

**Comment by A-SOM** [comment]
Подлил и поменял.
Проблему с 502 должно решить последний патч. Пожалуйста обновите репозиторий и попробуйте снова.
Извините за долгий support.
